export const LoginFormControls =[
    {
        label: 'Email',
        name: 'email',
        type: 'email',
        placeholder: 'Enter your email',
        required: true
    },
    {
        label: 'Password',
        name: 'password',
        type: 'password',
        placeholder: 'Enter your password',
        required: true
    }
]
export const registerFormControls =[
    {
        // label: 'User Name',
        name: 'userName',
        type: 'text',
        placeholder: 'First Name',
       required: true
    },
    {
        //label: 'Email',
        name: 'email',
        type: 'email',
        placeholder: 'Last Name',
        required: true
    },
    {
       // label: 'Password',
        name: 'password',
        type: 'password',
        placeholder: 'Enter your password',
       required: true
    },
    {
        //label: 'Confirm Password',
        name: 'confirmPassword',
        type: 'password',
        placeholder: 'Confirm your password',
       required: true
    },
    {
      name:'currency',
      label:'Currency  ',
      componentType:'select',
      options: [
  { id: "AED", label: "UAE Dirham" },
  { id: "AFN", label: "Afghan Afghani" },
  { id: "ALL", label: "Albanian Lek" },
  { id: "AMD", label: "Armenian Dram" },
  { id: "ANG", label: "Netherlands Antillean Guilder" },
  { id: "AOA", label: "Angolan Kwanza" },
  { id: "ARS", label: "Argentine Peso" },
  { id: "AUD", label: "Australian Dollar" },
  { id: "AWG", label: "Aruban Florin" },
  { id: "AZN", label: "Azerbaijani Manat" },
  { id: "BAM", label: "Bosnia-Herzegovina Convertible Mark" },
  { id: "BBD", label: "Barbadian Dollar" },
  { id: "BDT", label: "Bangladeshi Taka" },
  { id: "BGN", label: "Bulgarian Lev" },
  { id: "BHD", label: "Bahraini Dinar" },
  { id: "BIF", label: "Burundian Franc" },
  { id: "BMD", label: "Bermudian Dollar" },
  { id: "BND", label: "Brunei Dollar" },
  { id: "BOB", label: "Bolivian Boliviano" },
  { id: "BRL", label: "Brazilian Real" },
  { id: "BSD", label: "Bahamian Dollar" },
  { id: "BTN", label: "Bhutanese Ngultrum" },
  { id: "BWP", label: "Botswana Pula" },
  { id: "BYN", label: "Belarusian Ruble" },
  { id: "BZD", label: "Belize Dollar" },
  { id: "CAD", label: "Canadian Dollar" },
  { id: "CDF", label: "Congolese Franc" },
  { id: "CHF", label: "Swiss Franc" },
  { id: "CLP", label: "Chilean Peso" },
  { id: "CNY", label: "Chinese Yuan" },
  { id: "COP", label: "Colombian Peso" },
  { id: "CRC", label: "Costa Rican Colón" },
  { id: "CUP", label: "Cuban Peso" },
  { id: "CVE", label: "Cape Verdean Escudo" },
  { id: "CZK", label: "Czech Koruna" },
  { id: "DJF", label: "Djiboutian Franc" },
  { id: "DKK", label: "Danish Krone" },
  { id: "DOP", label: "Dominican Peso" },
  { id: "DZD", label: "Algerian Dinar" },
  { id: "EGP", label: "Egyptian Pound" },
  { id: "ERN", label: "Eritrean Nakfa" },
  { id: "ETB", label: "Ethiopian Birr" },
  { id: "EUR", label: "Euro" },
  { id: "FJD", label: "Fijian Dollar" },
  { id: "FKP", label: "Falkland Islands Pound" },
  { id: "FOK", label: "Faroese Króna" },
  { id: "GBP", label: "British Pound" },
  { id: "GEL", label: "Georgian Lari" },
  { id: "GGP", label: "Guernsey Pound" },
  { id: "GHS", label: "Ghanaian Cedi" },
  { id: "GIP", label: "Gibraltar Pound" },
  { id: "GMD", label: "Gambian Dalasi" },
  { id: "GNF", label: "Guinean Franc" },
  { id: "GTQ", label: "Guatemalan Quetzal" },
  { id: "GYD", label: "Guyanese Dollar" },
  { id: "HKD", label: "Hong Kong Dollar" },
  { id: "HNL", label: "Honduran Lempira" },
  { id: "HRK", label: "Croatian Kuna" },
  { id: "HTG", label: "Haitian Gourde" },
  { id: "HUF", label: "Hungarian Forint" },
  { id: "IDR", label: "Indonesian Rupiah" },
  { id: "ILS", label: "Israeli New Shekel" },
  { id: "IMP", label: "Isle of Man Pound" },
  { id: "INR", label: "Indian Rupee" },
  { id: "IQD", label: "Iraqi Dinar" },
  { id: "IRR", label: "Iranian Rial" },
  { id: "ISK", label: "Icelandic Króna" },
  { id: "JEP", label: "Jersey Pound" },
  { id: "JMD", label: "Jamaican Dollar" },
  { id: "JOD", label: "Jordanian Dinar" },
  { id: "JPY", label: "Japanese Yen" },
  { id: "KES", label: "Kenyan Shilling" },
  { id: "KGS", label: "Kyrgyzstani Som" },
  { id: "KHR", label: "Cambodian Riel" },
  { id: "KID", label: "Kiribati Dollar" },
  { id: "KMF", label: "Comorian Franc" },
  { id: "KRW", label: "South Korean Won" },
  { id: "KWD", label: "Kuwaiti Dinar" },
  { id: "KYD", label: "Cayman Islands Dollar" },
  { id: "KZT", label: "Kazakhstani Tenge" },
  { id: "LAK", label: "Lao Kip" },
  { id: "LBP", label: "Lebanese Pound" },
  { id: "LKR", label: "Sri Lankan Rupee" },
  { id: "LRD", label: "Liberian Dollar" },
  { id: "LSL", label: "Lesotho Loti" },
  { id: "LYD", label: "Libyan Dinar" },
  { id: "MAD", label: "Moroccan Dirham" },
  { id: "MDL", label: "Moldovan Leu" },
  { id: "MGA", label: "Malagasy Ariary" },
  { id: "MKD", label: "Macedonian Denar" },
  { id: "MMK", label: "Myanmar Kyat" },
  { id: "MNT", label: "Mongolian Tögrög" },
  { id: "MOP", label: "Macanese Pataca" },
  { id: "MRU", label: "Mauritanian Ouguiya" },
  { id: "MUR", label: "Mauritian Rupee" },
  { id: "MVR", label: "Maldivian Rufiyaa" },
  { id: "MWK", label: "Malawian Kwacha" },
  { id: "MXN", label: "Mexican Peso" },
  { id: "MYR", label: "Malaysian Ringgit" },
  { id: "MZN", label: "Mozambican Metical" },
  { id: "NAD", label: "Namibian Dollar" },
  { id: "NGN", label: "Nigerian Naira" },
  { id: "NIO", label: "Nicaraguan Córdoba" },
  { id: "NOK", label: "Norwegian Krone" },
  { id: "NPR", label: "Nepalese Rupee" },
  { id: "NZD", label: "New Zealand Dollar" },
  { id: "OMR", label: "Omani Rial" },
  { id: "PAB", label: "Panamanian Balboa" },
  { id: "PEN", label: "Peruvian Sol" },
  { id: "PGK", label: "Papua New Guinean Kina" },
  { id: "PHP", label: "Philippine Peso" },
  { id: "PKR", label: "Pakistani Rupee" },
  { id: "PLN", label: "Polish Złoty" },
  { id: "PYG", label: "Paraguayan Guaraní" },
  { id: "QAR", label: "Qatari Riyal" },
  { id: "RON", label: "Romanian Leu" },
  { id: "RSD", label: "Serbian Dinar" },
  { id: "RUB", label: "Russian Ruble" },
  { id: "RWF", label: "Rwandan Franc" },
  { id: "SAR", label: "Saudi Riyal" },
  { id: "SBD", label: "Solomon Islands Dollar" },
  { id: "SCR", label: "Seychellois Rupee" },
  { id: "SDG", label: "Sudanese Pound" },
  { id: "SEK", label: "Swedish Krona" },
  { id: "SGD", label: "Singapore Dollar" },
  { id: "SHP", label: "Saint Helena Pound" },
  { id: "SLL", label: "Sierra Leonean Leone" },
  { id: "SOS", label: "Somali Shilling" },
  { id: "SRD", label: "Surinamese Dollar" },
  { id: "SSP", label: "South Sudanese Pound" },
  { id: "STN", label: "São Tomé and Príncipe Dobra" },
  { id: "SYP", label: "Syrian Pound" },
  { id: "SZL", label: "Eswatini Lilangeni" },
  { id: "THB", label: "Thai Baht" },
  { id: "TJS", label: "Tajikistani Somoni" },
  { id: "TMT", label: "Turkmenistani Manat" },
  { id: "TND", label: "Tunisian Dinar" },
  { id: "TOP", label: "Tongan Paʻanga" },
  { id: "TRY", label: "Turkish Lira" },
  { id: "TTD", label: "Trinidad and Tobago Dollar" },
  { id: "TVD", label: "Tuvaluan Dollar" },
  { id: "TWD", label: "New Taiwan Dollar" },
  { id: "TZS", label: "Tanzanian Shilling" },
  { id: "UAH", label: "Ukrainian Hryvnia" },
  { id: "UGX", label: "Ugandan Shilling" },
  { id: "USD", label: "United States Dollar" },
  { id: "UYU", label: "Uruguayan Peso" },
  { id: "UZS", label: "Uzbekistani Soʻm" },
  { id: "VES", label: "Venezuelan Bolívar" },
  { id: "VND", label: "Vietnamese Đồng" },
  { id: "VUV", label: "Vanuatu Vatu" },
  { id: "WST", label: "Samoan Tālā" },
  { id: "XAF", label: "Central African CFA Franc" },
  { id: "XCD", label: "East Caribbean Dollar" },
  { id: "XOF", label: "West African CFA Franc" },
  { id: "XPF", label: "CFP Franc" },
  { id: "YER", label: "Yemeni Rial" },
  { id: "ZAR", label: "South African Rand" },
  { id: "ZMW", label: "Zambian Kwacha" },
  { id: "ZWL", label: "Zimbabwean Dollar" }
]
    },
    {
      label: "Gender",
      name: "gender",
      componentType: "select",
      options: [
       // { id:'', label :''},
        { id: "male", label: "Male" },
        { id: "female", label: "Female" },
      ],
    },
    {
      label: "Account Type",
      name: "accountType",
      componentType: "select",
      options: [
        // { id:' ', label :' '},
        { id: "onlineAccount", label: "Online Account" },
        { id: "checkingAccount", label: "Checking Account" },
        { id: "currentAccount", label: "Current Account" },
        { id: "corporateAccount", label: "Corporate Account" },
        { id: "offshoreAccount", label: "Offshore Account" },
        { id: "jointAccount", label: "Joint Account" },
      ],
    },

    {
      label: "Country",
      name: "country",
      componentType: "select",
      options : [
        { id: "Afghanistan", label: "Afghanistan" },
        { id: "Albania", label: "Albania" },
        { id: "Algeria", label: "Algeria" },
        { id: "Andorra", label: "Andorra" },
        { id: "Angola", label: "Angola" },
        { id: "Antigua and Barbuda", label: "Antigua and Barbuda" },
        { id: "Argentina", label: "Argentina" },
        { id: "Armenia", label: "Armenia" },
        { id: "Australia", label: "Australia" },
        { id: "Austria", label: "Austria" },
        { id: "Azerbaijan", label: "Azerbaijan" },
        { id: "Bahamas", label: "Bahamas" },
        { id: "Bahrain", label: "Bahrain" },
        { id: "Bangladesh", label: "Bangladesh" },
        { id: "Barbados", label: "Barbados" },
        { id: "Belarus", label: "Belarus" },
        { id: "Belgium", label: "Belgium" },
        { id: "Belize", label: "Belize" },
        { id: "Benin", label: "Benin" },
        { id: "Bhutan", label: "Bhutan" },
        { id: "Bolivia", label: "Bolivia" },
        { id: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
        { id: "Botswana", label: "Botswana" },
        { id: "Brazil", label: "Brazil" },
        { id: "Brunei", label: "Brunei" },
        { id: "Bulgaria", label: "Bulgaria" },
        { id: "Burkina Faso", label: "Burkina Faso" },
        { id: "Burundi", label: "Burundi" },
        { id: "Cambodia", label: "Cambodia" },
        { id: "Cameroon", label: "Cameroon" },
        { id: "Canada", label: "Canada" },
        { id: "Cape Verde", label: "Cape Verde" },
        { id: "Central African Republic", label: "Central African Republic" },
        { id: "Chad", label: "Chad" },
        { id: "Chile", label: "Chile" },
        { id: "China", label: "China" },
        { id: "Colombia", label: "Colombia" },
        { id: "Comoros", label: "Comoros" },
        { id: "Congo (Brazzaville)", label: "Congo (Brazzaville)" },
        { id: "Congo (Kinshasa)", label: "Congo (Kinshasa)" },
        { id: "Costa Rica", label: "Costa Rica" },
        { id: "Croatia", label: "Croatia" },
        { id: "Cuba", label: "Cuba" },
        { id: "Cyprus", label: "Cyprus" },
        { id: "Czech Republic", label: "Czech Republic" },
        { id: "Denmark", label: "Denmark" },
        { id: "Djibouti", label: "Djibouti" },
        { id: "Dominica", label: "Dominica" },
        { id: "Dominican Republic", label: "Dominican Republic" },
        { id: "Ecuador", label: "Ecuador" },
        { id: "Egypt", label: "Egypt" },
        { id: "El Salvador", label: "El Salvador" },
        { id: "Equatorial Guinea", label: "Equatorial Guinea" },
        { id: "Eritrea", label: "Eritrea" },
        { id: "Estonia", label: "Estonia" },
        { id: "Eswatini", label: "Eswatini" },
        { id: "Ethiopia", label: "Ethiopia" },
        { id: "Fiji", label: "Fiji" },
        { id: "Finland", label: "Finland" },
        { id: "France", label: "France" },
        { id: "Gabon", label: "Gabon" },
        { id: "Gambia", label: "Gambia" },
        { id: "Georgia", label: "Georgia" },
        { id: "Germany", label: "Germany" },
        { id: "Ghana", label: "Ghana" },
        { id: "Greece", label: "Greece" },
        { id: "Grenada", label: "Grenada" },
        { id: "Guatemala", label: "Guatemala" },
        { id: "Guinea", label: "Guinea" },
        { id: "Guinea-Bissau", label: "Guinea-Bissau" },
        { id: "Guyana", label: "Guyana" },
        { id: "Haiti", label: "Haiti" },
        { id: "Honduras", label: "Honduras" },
        { id: "Hungary", label: "Hungary" },
        { id: "Iceland", label: "Iceland" },
        { id: "India", label: "India" },
        { id: "Indonesia", label: "Indonesia" },
        { id: "Iran", label: "Iran" },
        { id: "Iraq", label: "Iraq" },
        { id: "Ireland", label: "Ireland" },
        { id: "Israel", label: "Israel" },
        { id: "Italy", label: "Italy" },
        { id: "Jamaica", label: "Jamaica" },
        { id: "Japan", label: "Japan" },
        { id: "Jordan", label: "Jordan" },
        { id: "Kazakhstan", label: "Kazakhstan" },
        { id: "Kenya", label: "Kenya" },
        { id: "Kiribati", label: "Kiribati" },
        { id: "Kuwait", label: "Kuwait" },
        { id: "Kyrgyzstan", label: "Kyrgyzstan" },
        { id: "Laos", label: "Laos" },
        { id: "Latvia", label: "Latvia" },
        { id: "Lebanon", label: "Lebanon" },
        { id: "Lesotho", label: "Lesotho" },
        { id: "Liberia", label: "Liberia" },
        { id: "Libya", label: "Libya" },
        { id: "Liechtenstein", label: "Liechtenstein" },
        { id: "Lithuania", label: "Lithuania" },
        { id: "Luxembourg", label: "Luxembourg" },
        { id: "Madagascar", label: "Madagascar" },
        { id: "Malawi", label: "Malawi" },
        { id: "Malaysia", label: "Malaysia" },
        { id: "Maldives", label: "Maldives" },
        { id: "Mali", label: "Mali" },
        { id: "Malta", label: "Malta" },
        { id: "Marshall Islands", label: "Marshall Islands" },
        { id: "Mauritania", label: "Mauritania" },
        { id: "Mauritius", label: "Mauritius" },
        { id: "Mexico", label: "Mexico" },
        { id: "Micronesia", label: "Micronesia" },
        { id: "Moldova", label: "Moldova" },
        { id: "Monaco", label: "Monaco" },
        { id: "Mongolia", label: "Mongolia" },
        { id: "Montenegro", label: "Montenegro" },
        { id: "Morocco", label: "Morocco" },
        { id: "Mozambique", label: "Mozambique" },
        { id: "Myanmar", label: "Myanmar" },
        { id: "Namibia", label: "Namibia" },
        { id: "Nauru", label: "Nauru" },
        { id: "Nepal", label: "Nepal" },
        { id: "Netherlands", label: "Netherlands" },
        { id: "New Zealand", label: "New Zealand" },
        { id: "Nicaragua", label: "Nicaragua" },
        { id: "Niger", label: "Niger" },
        { id: "Nigeria", label: "Nigeria" },
        { id: "North Korea", label: "North Korea" },
        { id: "North Macedonia", label: "North Macedonia" },
        { id: "Norway", label: "Norway" },
        { id: "Oman", label: "Oman" },
        { id: "Pakistan", label: "Pakistan" },
        { id: "Palau", label: "Palau" },
        { id: "Panama", label: "Panama" },
        { id: "Papua New Guinea", label: "Papua New Guinea" },
        { id: "Paraguay", label: "Paraguay" },
        { id: "Peru", label: "Peru" },
        { id: "Philippines", label: "Philippines" },
        { id: "Poland", label: "Poland" },
        { id: "Portugal", label: "Portugal" },
        { id: "Qatar", label: "Qatar" },
        { id: "Romania", label: "Romania" },
        { id: "Russia", label: "Russia" },
        { id: "Rwanda", label: "Rwanda" },
        { id: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
        { id: "Saint Lucia", label: "Saint Lucia" },
        { id: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines" },
        { id: "Samoa", label: "Samoa" },
        { id: "San Marino", label: "San Marino" },
        { id: "Sao Tome and Principe", label: "Sao Tome and Principe" },
        { id: "Saudi Arabia", label: "Saudi Arabia" },
        { id: "Senegal", label: "Senegal" },
        { id: "Serbia", label: "Serbia" },
        { id: "Seychelles", label: "Seychelles" },
        { id: "Sierra Leone", label: "Sierra Leone" },
        { id: "Singapore", label: "Singapore" },
        { id: "Slovakia", label: "Slovakia" },
        { id: "Slovenia", label: "Slovenia" },
        { id: "Solomon Islands", label: "Solomon Islands" },
        { id: "Somalia", label: "Somalia" },
        { id: "South Africa", label: "South Africa" },
        { id: "South Korea", label: "South Korea" },
        { id: "South Sudan", label: "South Sudan" },
        { id: "Spain", label: "Spain" },
        { id: "Sri Lanka", label: "Sri Lanka" },
        { id: "Sudan", label: "Sudan" },
        { id: "Suriname", label: "Suriname" },
        { id: "Sweden", label: "Sweden" },
        { id: "Switzerland", label: "Switzerland" },
        { id: "Syria", label: "Syria" },
        { id: "Taiwan", label: "Taiwan" },
        { id: "Tajikistan", label: "Tajikistan" },
        { id: "Tanzania", label: "Tanzania" },
        { id: "Thailand", label: "Thailand" },
        { id: "Timor-Leste", label: "Timor-Leste" },
        { id: "Togo", label: "Togo" },
        { id: "Tonga", label: "Tonga" },
        { id: "Trinidad and Tobago", label: "Trinidad and Tobago" },
        { id: "Tunisia", label: "Tunisia" },
        { id: "Turkey", label: "Turkey" },
        { id: "Turkmenistan", label: "Turkmenistan" },
        { id: "Tuvalu", label: "Tuvalu" },
        { id: "Uganda", label: "Uganda" },
        { id: "Ukraine", label: "Ukraine" },
        { id: "United Arab Emirates", label: "United Arab Emirates" },
        { id: "United Kingdom", label: "United Kingdom" },
        { id: "United States", label: "United States" },
        { id: "Uruguay", label: "Uruguay" },
        { id: "Uzbekistan", label: "Uzbekistan" },
        { id: "Vanuatu", label: "Vanuatu" },
        { id: "Vatican City", label: "Vatican City" },
        { id: "Venezuela", label: "Venezuela" },
        { id: "Vietnam", label: "Vietnam" },
        { id: "Yemen", label: "Yemen" },
        { id: "Zambia", label: "Zambia" },
        { id: "Zimbabwe", label: "Zimbabwe" }
      ],
    },
];
export const ManagementViewHeaderMenuItems = [
    {
      id: "home",
      label: "Home",
      path: "/shop/home",
    },
    {
      id: "footwear",
      label: "Footwear",
      path: "/shop/listing",
    },
    {
      id: "accessories",
      label: "Accessories",
      path: "/shop/listing",
    },
    {
      id: "search",
      label: "Search",
      path: "/shop/search",
    },
  ];
  export const addEmployeeFormElements = [
    {
      label: "Name",
      name: "name",
      componentType: "input",
      type: "text",
      placeholder: "Enter product title",
    },
    {
      label: "Description",
      name: "description",
      componentType: "textarea",
      placeholder: "Enter product description",
    },
    {
      label: "Gender",
      name: "gender",
      componentType: "select",
      options: [
        { id: "male", label: "Male" },
        { id: "female", label: "Female" },
      ],
    },
    {
      label: "Contract type",
      name: "contract",
      componentType: "select",
      options: [
        { id: "longTerm", label: "Long Term" },
        { id: "shortTerm", label: "Short Term" },
      ],
    },
    {
      label: "Department",
      name: "department",
      componentType: "select",
      options: [
        { id: "sales", label: "Sales" },
        { id: "Marketing", label: "Marketing" },
        { id: "Developer", label: "Developer" },
        { id: "partner", label: "Partner" },
        { id: "ceo", label: "CEO" },
        { id: "Field", label: "field" },
      ],
    },
    {
      label: "Salary",
      name: "salary",
      componentType: "input",
      type: "number",
      placeholder: "Enter his/her price",
    },
    {
      label: "Email",
      name: "email",
      componentType: "input",
      type: "email",
      placeholder: "Enter his/her Email",
    },
    
  ];